import Fastify from 'fastify';
import rateLimit from '@fastify/rate-limit';
import {randomUUID} from 'node:crypto';
import {Keypair,PublicKey} from '@solana/web3.js';
import bs58 from 'bs58';
import {z} from 'zod';
import {requireThat,seal,unseal,zcashTAddress} from './security.mjs';
const url=z.string().url().refine(value=>value.startsWith('https://')).nullable().optional();
const inputSchema=z.object({name:z.string().trim().min(2).max(32),symbol:z.string().regex(/^[A-Z0-9]{2,10}$/),description:z.string().max(1000),wallet:z.string().min(32).max(44),image:z.string().max(1200000),rewardMode:z.enum(['holder','creator']),zecAddress:z.string().nullable(),creatorFeeBps:z.number().int().min(0).max(10000).nullable(),initialBuyRaw:z.string().regex(/^\d{1,18}$/),website:url,twitter:url,telegram:url});
const publicFields='l.id,l.mint,l.name,l.symbol,l.description,l.owner_wallet AS wallet,l.reward_mode,l.zec_address,l.creator_fee_bps,l.status,l.created_at,l.confirmed_at,l.website,l.twitter,l.telegram,COALESCE(c.collected_raw,0)::text AS collected_raw,COALESCE(p.paid_raw,0)::text AS paid_raw';
const joined=` FROM launches l LEFT JOIN (SELECT launch_id,sum(amount_raw) AS collected_raw FROM fee_sweeps WHERE status='confirmed' GROUP BY launch_id) c ON c.launch_id=l.id LEFT JOIN (SELECT launch_id,sum(COALESCE(native_amount_raw,0)) AS paid_raw FROM native_payouts WHERE status='confirmed' GROUP BY launch_id) p ON p.launch_id=l.id `;
const present=row=>({...row,image_url:`/api/images/${row.id}`});
export async function appFactory({db,config,chain}){
 const app=Fastify({bodyLimit:1300000,logger:false,trustProxy:1});await app.register(rateLimit,{max:90,timeWindow:'1 minute'});
 app.setErrorHandler((error,req,reply)=>{const code=error.statusCode||((error.name==='ZodError'||error.name==='SyntaxError')?400:500);if(code>=500)req.log.error({code:error.code||error.name,requestId:req.id},'API error');reply.code(code).send({error:code>=500?'Service is unavailable. Try again shortly.':error.message})});
 app.addHook('onRequest',async(req,reply)=>{if(req.method==='POST'){requireThat(req.headers.origin===config.origin,403,'Request origin does not match this site');reply.header('Cache-Control','no-store')}if(req.url.startsWith('/api/')&&!req.url.startsWith('/api/images/')&&!req.url.startsWith('/api/metadata/'))reply.header('Cache-Control','no-store')});
 app.get('/api/health',async()=>{await db.query('SELECT 1');return {ok:true}});
 app.get('/api/status',async()=>{const payout=Boolean(config.nativePayoutsEnabled&&config.collectionsEnabled&&config.oneClickApiKey&&config.treasurySecret&&config.operatorSecret);return {ready:Boolean(config.database&&config.rpc),launches:Boolean(config.launchesEnabled&&config.rpc&&config.encryptionKey&&config.database),quoteMint:config.quoteMint,quoteDecimals:8,bridge:payout?'automatic':'disabled',nativePayouts:payout,cluster:config.cluster}});
 app.get('/api/tokens',async()=>{const {rows}=await db.query(`SELECT ${publicFields} ${joined} WHERE l.status='confirmed' ORDER BY l.confirmed_at DESC LIMIT 120`);return {tokens:rows.map(present)}});
 app.get('/api/token/:id',async req=>{const {rows:[row]}=await db.query(`SELECT ${publicFields} ${joined} WHERE l.status='confirmed' AND l.id=$1`,[req.params.id]);requireThat(row,404,'Token not found');return present(row)});
 app.get('/api/payouts',async()=>{const {rows}=await db.query("SELECT p.id,p.launch_id,p.amount_raw::text,p.native_amount_raw::text,p.destination,p.status,p.zec_txid,p.created_at,l.name AS token_name FROM native_payouts p JOIN launches l ON l.id=p.launch_id WHERE l.status='confirmed' AND p.status IN ('submitted','processing','confirmed','refunded','needs_review') ORDER BY p.created_at DESC LIMIT 60");return {payouts:rows}});
 app.get('/api/images/:id',async(req,reply)=>{const {rows:[row]}=await db.query('SELECT image_type,image_bytes FROM launches WHERE id=$1 AND status IN (\'prepared\',\'submitted\',\'confirmed\')',[req.params.id]);requireThat(row,404,'Image not found');return reply.type(row.image_type).header('Cache-Control','public,max-age=86400').send(row.image_bytes)});
 app.get('/api/metadata/:id',async(req,reply)=>{const {rows:[row]}=await db.query("SELECT name,symbol,description,website,twitter,telegram FROM launches WHERE id=$1 AND status IN ('prepared','submitted','confirmed')",[req.params.id]);requireThat(row,404,'Token metadata not found');return reply.header('Cache-Control','public,max-age=300').send({name:row.name,symbol:row.symbol,description:row.description,image:`${config.origin}/api/images/${req.params.id}`,showName:true,...(row.website?{website:row.website}:{}),...(row.twitter?{twitter:row.twitter}:{}),...(row.telegram?{telegram:row.telegram}:{})})});
 app.post('/api/launch/prepare',{config:{rateLimit:{max:5,timeWindow:'10 minutes'}}},async req=>{
  requireThat(config.launchesEnabled,503,'Launch service is paused');requireThat(config.rpc&&config.encryptionKey&&config.database,503,'Launch service is not configured');const input=inputSchema.parse(req.body);
  let wallet;try{wallet=new PublicKey(input.wallet)}catch{requireThat(false,400,'Invalid Solana wallet address')}
  requireThat(Buffer.byteLength(input.name,'utf8')<=32,400,'Token name exceeds 32 bytes');requireThat(input.rewardMode==='creator'?zcashTAddress(input.zecAddress):input.zecAddress===null,400,'Enter a valid transparent Zcash t-address for creator payouts');requireThat(input.rewardMode==='creator'||input.creatorFeeBps===null,400,'Holder rewards use the Pump fee schedule');
  if(input.rewardMode==='creator')requireThat(config.collectionsEnabled&&config.nativePayoutsEnabled&&config.operatorSecret&&config.treasurySecret&&config.oneClickApiKey,503,'Creator payouts are not configured yet. Holder rewards are available when launches are enabled');
  const image=input.image.match(/^data:(image\/png|image\/jpeg|image\/webp|image\/gif);base64,([A-Za-z0-9+/=]+)$/);requireThat(image,400,'Provide a PNG, JPG, WebP or GIF');const bytes=Buffer.from(image[2],'base64');requireThat(bytes.length>0&&bytes.length<=800000,400,'Artwork must be under 800 KB');
  const {rows:[active]}=await db.query("SELECT count(*)::int AS n FROM launches WHERE owner_wallet=$1 AND status IN ('preparing','prepared','submitted') AND created_at>now()-interval '30 minutes'",[wallet.toBase58()]);requireThat(active.n<2,429,'Finish your current launch before preparing another');
  const id=randomUUID(),mint=Keypair.generate(),creator=input.rewardMode==='creator'?Keypair.generate():null;
  const values=[id,wallet.toBase58(),input.name,input.symbol,input.description,mint.publicKey.toBase58(),seal(mint.secretKey,config.encryptionKey,`mint:${id}`),creator?.publicKey.toBase58()||wallet.toBase58(),creator?seal(creator.secretKey,config.encryptionKey,`creator:${id}`):null,image[1],bytes,input.rewardMode,input.zecAddress,input.creatorFeeBps,input.initialBuyRaw,input.website||null,input.twitter||null,input.telegram||null,config.quoteMint];
  await db.query('INSERT INTO launches(id,owner_wallet,name,symbol,description,mint,mint_secret,creator,creator_secret,image_type,image_bytes,reward_mode,zec_address,creator_fee_bps,initial_buy_raw,website,twitter,telegram,quote_mint) VALUES('+values.map((_,i)=>`$${i+1}`).join(',')+')',values);
  try{const row=(await db.query('SELECT * FROM launches WHERE id=$1',[id])).rows[0];const prepared=await chain.prepare(row);await db.query("UPDATE launches SET status='prepared',message_base64=$2,transaction_base64=$3,last_valid_height=$4 WHERE id=$1",[id,prepared.message,prepared.wire,prepared.lastValidHeight]);return {id,mint:row.mint,transaction:prepared.wire,network:'Solana '+config.cluster}}
  catch(error){await db.query("UPDATE launches SET status='failed',error=$2 WHERE id=$1",[id,error.statusCode<500?error.message:'Launch preparation unavailable']);throw error}
 });
 app.post('/api/launch/:id/submit',{config:{rateLimit:{max:10,timeWindow:'10 minutes'}}},async req=>{
  requireThat(config.launchesEnabled,503,'Launch service is paused');requireThat(typeof req.body?.transaction==='string'&&req.body.transaction.length<5000,400,'Signed transaction required');
  const row=await db.transaction(async tx=>{const {rows:[item]}=await tx.query('SELECT * FROM launches WHERE id=$1 FOR UPDATE',[req.params.id]);requireThat(item,404,'Launch not found');if(item.status==='submitted'||item.status==='confirmed')return item;requireThat(item.status==='prepared',409,'Launch is no longer awaiting a signature');requireThat(await chain.connection.getBlockHeight('confirmed')<=item.last_valid_height,409,'Launch quote expired; prepare a new launch');const signed=chain.verifyWalletWire(req.body.transaction,item.message_base64,item.owner_wallet),mint=Keypair.fromSecretKey(unseal(item.mint_secret,config.encryptionKey,`mint:${item.id}`));signed.sign([mint]);const wire=Buffer.from(signed.serialize()).toString('base64'),sig=bs58.encode(signed.signatures[0]);return (await tx.query("UPDATE launches SET status='submitted',transaction_base64=$2,signature=$3 WHERE id=$1 RETURNING *",[item.id,wire,sig])).rows[0]});
  if(row.status==='submitted'){try{await chain.send(row.transaction_base64)}catch{/* persisted signed wire is retried by worker */}}
  return {id:row.id,status:row.status,signature:row.signature};
 });
 app.get('/api/launch/:id',async req=>{const {rows:[row]}=await db.query('SELECT id,status,error,signature,mint FROM launches WHERE id=$1',[req.params.id]);requireThat(row,404,'Launch not found');return row});
 return app;
}
