import {Connection,ComputeBudgetProgram,Keypair,PublicKey,TransactionMessage,VersionedTransaction} from '@solana/web3.js';
import {PUMP_SDK,OnlinePumpSdk,getBuyTokenAmountFromSolAmount,holderRewardsPda} from '@pump-fun/pump-sdk';
import {TOKEN_2022_PROGRAM_ID,TOKEN_PROGRAM_ID,createAssociatedTokenAccountIdempotentInstruction,createTransferCheckedInstruction,getAssociatedTokenAddressSync} from '@solana/spl-token';
import BN from 'bn.js';
import bs58 from 'bs58';
import nacl from 'tweetnacl';
import {keypair,requireThat,unseal} from './security.mjs';

const expectedHash={'mainnet-beta':'5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d','devnet':'EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG'};
export function chain(config){
 const connection=new Connection(config.rpc,{commitment:'confirmed',disableRetryOnRateLimit:true,fetch:(url,init)=>fetch(url,{...init,signal:AbortSignal.timeout(20000)})});
 const sdk=new OnlinePumpSdk(connection),quoteMint=new PublicKey(config.quoteMint);
 let checked=false,quoteProgram,quoteDecimals;
 async function network(){if(checked)return;requireThat(config.rpc,503,'SOLANA_RPC_URL is missing');const hash=await connection.getGenesisHash();requireThat(hash===expectedHash[config.cluster],503,'RPC network does not match SOLANA_CLUSTER');const info=await connection.getParsedAccountInfo(quoteMint);requireThat(info.value,503,'ZEC mint is not present on this network');quoteProgram=info.value.owner;quoteDecimals=info.value.data?.parsed?.info?.decimals;requireThat(Number.isInteger(quoteDecimals)&&quoteDecimals===8,503,'ZEC mint decimals do not match the expected 8');checked=true}
 async function createTx(instructions,payer,signers=[]){await network();const latest=await connection.getLatestBlockhash('confirmed');const msg=new TransactionMessage({payerKey:payer,recentBlockhash:latest.blockhash,instructions:[ComputeBudgetProgram.setComputeUnitLimit({units:650000}),...instructions]}).compileToV0Message();const tx=new VersionedTransaction(msg);if(signers.length)tx.sign(signers);const wire=Buffer.from(tx.serialize()).toString('base64');requireThat(Buffer.byteLength(wire,'base64')<=1232,422,'Transaction exceeds the Solana size limit');return {tx,wire,message:Buffer.from(msg.serialize()).toString('base64'),lastValidHeight:latest.lastValidBlockHeight,signature:bs58.encode(tx.signatures[0])}}
 async function simulation(tx){const response=await connection.simulateTransaction(tx,{sigVerify:false,commitment:'confirmed'});if(response.value.err){const text=JSON.stringify(response.value.err);throw Object.assign(new Error(`Pump transaction simulation failed: ${text.slice(0,180)}`),{statusCode:422})}}
 async function prepare(row){await network();const mint=Keypair.fromSecretKey(unseal(row.mint_secret,config.encryptionKey,`mint:${row.id}`)),user=new PublicKey(row.owner_wallet),creator=row.reward_mode==='holder'?user:Keypair.fromSecretKey(unseal(row.creator_secret,config.encryptionKey,`creator:${row.id}`)).publicKey;
  requireThat(mint.publicKey.toBase58()===row.mint,500,'Mint signer mismatch');const global=await sdk.fetchGlobal();
  const args={mint:mint.publicKey,name:row.name,symbol:row.symbol,uri:`${config.origin}/api/metadata/${row.id}`,creator,user,mayhemMode:false,quoteMint,quoteTokenProgram:quoteProgram,holderReward:row.reward_mode==='holder',...(row.creator_fee_bps!==null?{creatorFeeBps:new BN(String(row.creator_fee_bps))}:{})};
  // On a token-quoted curve, the new-curve quote control sets virtual reserves.
  const buyRaw=BigInt(row.initial_buy_raw),instructions=buyRaw>0n?await (async()=>{const feeConfig=await sdk.fetchFeeConfig(),quoteControl=await sdk.fetchQuoteControl(),amount=getBuyTokenAmountFromSolAmount({global,feeConfig,mintSupply:null,bondingCurve:null,amount:new BN(buyRaw.toString()),quoteMint,quoteControl,creatorFeeBps:row.creator_fee_bps!==null?new BN(String(row.creator_fee_bps)):undefined});requireThat(amount.gtn(0),422,'Initial ZEC buy is too small');const userZec=getAssociatedTokenAddressSync(quoteMint,user,false,quoteProgram);const balance=await connection.getTokenAccountBalance(userZec).catch(()=>null);requireThat(balance&&BigInt(balance.value.amount)>=buyRaw,422,'Wallet needs ZEC on Solana for the initial buy');return PUMP_SDK.createV2AndBuyV2Instructions({...args,global,amount,quoteAmount:new BN(buyRaw.toString())})})():[await PUMP_SDK.createV2Instruction(args)];
  const built=await createTx(instructions,user,[mint]);await simulation(built.tx);return built;
 }
 function verifyWalletWire(wire,original,owner){let tx;try{tx=VersionedTransaction.deserialize(Buffer.from(wire,'base64'))}catch{requireThat(false,400,'Wallet returned an invalid transaction')}requireThat(Buffer.from(tx.message.serialize()).toString('base64')===original,400,'The signed transaction was modified');const index=tx.message.staticAccountKeys.findIndex(k=>k.toBase58()===owner);requireThat(index>=0&&index<tx.message.header.numRequiredSignatures,403,'Wallet signer is missing');requireThat(nacl.sign.detached.verify(tx.message.serialize(),tx.signatures[index],new PublicKey(owner).toBytes()),403,'Wallet signature is invalid');return tx}
 async function state(signature,height){const status=(await connection.getSignatureStatuses([signature],{searchTransactionHistory:true})).value[0];if(status?.confirmationStatus==='finalized')return status.err?'failed':'confirmed';if(status)return 'pending';return await connection.getBlockHeight('finalized')>Number(height)?'expired':'pending'}
 async function send(wire){return connection.sendRawTransaction(Buffer.from(wire,'base64'),{skipPreflight:false,maxRetries:2})}
 async function checkLaunch(row){const curve=await sdk.fetchBondingCurve(new PublicKey(row.mint));requireThat(curve.quoteMint?.toBase58()===config.quoteMint,409,'Wrong quote mint on chain');requireThat(Boolean(curve.isHolderReward)===Boolean(row.reward_mode==='holder'),409,'Reward mode does not match on chain');if(row.reward_mode==='creator')requireThat(curve.creator.toBase58()===row.creator,409,'Creator fee destination does not match on chain');return curve}
 async function due(row){await network();const values=await sdk.getCreatorVaultQuoteBalances(new PublicKey(row.creator));const matching=values.find(v=>v.mint.equals(quoteMint));return matching?BigInt(matching.total.toString()):0n}
 async function collect(row){await network();const operator=keypair(config.operatorSecret),creator=new PublicKey(row.creator),ata=getAssociatedTokenAddressSync(quoteMint,creator,false,quoteProgram),instructions=[createAssociatedTokenAccountIdempotentInstruction(operator.publicKey,ata,creator,quoteMint,quoteProgram),...await sdk.collectCoinCreatorFeeV2Instructions(creator,quoteMint,quoteProgram,operator.publicKey)];const tx=await createTx(instructions,operator.publicKey,[operator]);await simulation(tx.tx);return tx}
 async function received(signature,address){const tx=await connection.getTransaction(signature,{commitment:'finalized',maxSupportedTransactionVersion:0});requireThat(tx&&!tx.meta?.err,503,'Finalized token transfer receipt is not available');const keys=tx.transaction.message.getAccountKeys({accountKeysFromLookups:tx.meta.loadedAddresses});const index=Array.from({length:keys.length},(_,i)=>keys.get(i)?.toBase58()).indexOf(address);requireThat(index>=0,500,'Token destination is missing from receipt');const find=(values)=>BigInt(values?.find(v=>v.accountIndex===index&&v.mint===config.quoteMint)?.uiTokenAmount?.amount||'0');const amount=find(tx.meta.postTokenBalances)-find(tx.meta.preTokenBalances);requireThat(amount>0n,503,'No finalized ZEC received at token destination');return amount}
 async function move({source,destination,amount}){await network();const operator=keypair(config.operatorSecret),sender=keypair(source),mint=quoteMint,to=new PublicKey(destination),src=getAssociatedTokenAddressSync(mint,sender.publicKey,false,quoteProgram),dest=getAssociatedTokenAddressSync(mint,to,false,quoteProgram);const instructions=[createAssociatedTokenAccountIdempotentInstruction(operator.publicKey,dest,to,mint,quoteProgram),createTransferCheckedInstruction(src,mint,dest,sender.publicKey,amount,quoteDecimals,[],quoteProgram)];const built=await createTx(instructions,operator.publicKey,[operator,sender]);await simulation(built.tx);return {...built,destinationAta:dest.toBase58()}}
 async function tokenBalance(owner){await network();const ata=getAssociatedTokenAddressSync(quoteMint,new PublicKey(owner),false,quoteProgram);const info=await connection.getTokenAccountBalance(ata).catch(()=>null);return info?BigInt(info.value.amount):0n}
 return {connection,sdk,network,prepare,verifyWalletWire,state,send,checkLaunch,due,collect,received,move,tokenBalance,quoteMint,quoteProgram:()=>quoteProgram,quoteDecimals:()=>quoteDecimals};
}
