import {randomUUID} from 'node:crypto';
import {Keypair} from '@solana/web3.js';
import {getAssociatedTokenAddressSync} from '@solana/spl-token';
import {chain as createChain} from './chain.mjs';
import {oneClick} from './bridge.mjs';
import {configuration} from './config.mjs';
import {database} from './db.mjs';
import {keypair,unseal,requireThat} from './security.mjs';

export async function tick({db,config,chain,bridge}){
 // Reconcile all signed launch wires, even when new launches have been paused.
 const {rows:launches}=await db.query("SELECT * FROM launches WHERE status='submitted' ORDER BY created_at LIMIT 25");
 for(const row of launches){try{const result=await chain.state(row.signature,row.last_valid_height);if(result==='confirmed'){await chain.checkLaunch(row);await db.query("UPDATE launches SET status='confirmed',confirmed_at=now(),mint_secret='',creator_secret=CASE WHEN reward_mode='holder' THEN NULL ELSE creator_secret END WHERE id=$1",[row.id])}else if(result==='expired'||result==='failed')await db.query('UPDATE launches SET status=$2,error=$3 WHERE id=$1',[row.id,result,'Transaction failed or expired']);else await chain.send(row.transaction_base64).catch(()=>{})}catch(error){console.error(JSON.stringify({event:'launch_reconcile_retry',id:row.id,code:error.code||error.name}))}}

 // Each creator-mode launch gets a different creator key: vault receipts cannot
 // be misattributed to another launch, even if 50 markets share one treasury.
 if(config.collectionsEnabled&&config.operatorSecret){const {rows:eligible}=await db.query("SELECT l.* FROM launches l WHERE l.status='confirmed' AND l.reward_mode='creator' AND NOT EXISTS (SELECT 1 FROM fee_collections c WHERE c.launch_id=l.id AND c.status IN ('preparing','submitted')) AND NOT EXISTS (SELECT 1 FROM fee_sweeps s WHERE s.launch_id=l.id AND s.status IN ('reserved','submitted','failed')) ORDER BY l.confirmed_at LIMIT 25");for(const row of eligible){try{const due=await chain.due(row);if(due<config.minPayout)continue;const collection=await chain.collect(row);await db.query("INSERT INTO fee_collections(id,launch_id,signature,amount_raw,status,wire_base64,last_valid_height) VALUES($1,$2,$3,1,'submitted',$4,$5)",[randomUUID(),row.id,collection.signature,collection.wire,collection.lastValidHeight]);await chain.send(collection.wire).catch(()=>{})}catch(error){console.error(JSON.stringify({event:'collect_retry',launchId:row.id,code:error.code||error.name}))}}}
 const {rows:collections}=await db.query("SELECT c.*,l.creator FROM fee_collections c JOIN launches l ON l.id=c.launch_id WHERE c.status='submitted' ORDER BY c.created_at LIMIT 25");
 for(const item of collections){try{const state=await chain.state(item.signature,item.last_valid_height);if(state==='pending'){await chain.send(item.wire_base64).catch(()=>{});continue}if(state!=='confirmed'){await db.query("UPDATE fee_collections SET status='failed',error=$2 WHERE id=$1",[item.id,'Collection transaction failed or expired']);continue}const creatorAta=getAssociatedTokenAddressSync(chain.quoteMint,new (await import('@solana/web3.js')).PublicKey(item.creator),false,chain.quoteProgram()).toBase58(),amount=await chain.received(item.signature,creatorAta);await db.transaction(async tx=>{await tx.query("UPDATE fee_collections SET status='confirmed',amount_raw=$2,confirmed_at=now() WHERE id=$1",[item.id,String(amount)]);await tx.query("INSERT INTO fee_sweeps(id,launch_id,amount_raw,status) VALUES($1,$2,$3,'reserved') ON CONFLICT DO NOTHING",[item.id,item.launch_id,String(amount)])})}catch(error){console.error(JSON.stringify({event:'collection_reconcile_retry',id:item.id,code:error.code||error.name}))}}

 const {rows:sweeps}=await db.query("SELECT s.*,l.creator_secret,l.creator FROM fee_sweeps s JOIN launches l ON l.id=s.launch_id WHERE s.status IN ('reserved','submitted') ORDER BY s.created_at LIMIT 20");
 for(const item of sweeps){try{if(!config.treasurySecret||!config.operatorSecret)continue;const treasury=keypair(config.treasurySecret);let current=item;if(item.status==='reserved'){requireThat(item.creator_secret,503,'Creator signer is unavailable');const creator=Keypair.fromSecretKey(unseal(item.creator_secret,config.encryptionKey,`creator:${item.launch_id}`));requireThat(creator.publicKey.toBase58()===item.creator,500,'Creator signer mismatch');const prepared=await chain.move({source:creator.secretKey,destination:treasury.publicKey.toBase58(),amount:BigInt(item.amount_raw)});
   current=(await db.query("UPDATE fee_sweeps SET status='submitted',signature=$2,wire_base64=$3,last_valid_height=$4 WHERE id=$1 RETURNING *",[item.id,prepared.signature,prepared.wire,prepared.lastValidHeight])).rows[0];}
  const status=await chain.state(current.signature,current.last_valid_height);if(status==='confirmed'){const ata=getAssociatedTokenAddressSync(chain.quoteMint,treasury.publicKey,false,chain.quoteProgram()).toBase58();const receipt=await chain.received(current.signature,ata);requireThat(receipt===BigInt(item.amount_raw),503,'Swept amount does not match collection');await db.query("UPDATE fee_sweeps SET status='confirmed' WHERE id=$1",[item.id])}else if(status==='failed'||status==='expired')await db.query("UPDATE fee_sweeps SET status='failed' WHERE id=$1",[item.id]);else await chain.send(current.wire_base64).catch(()=>{})}catch(error){console.error(JSON.stringify({event:'sweep_retry',id:item.id,code:error.code||error.name}))}}

 // Native payouts are opt-in. Reserve only finalized swept amounts and cap a
 // single transfer. Never retry a transfer with a different quote after deposit.
 if(config.nativePayoutsEnabled&&config.oneClickApiKey&&config.treasurySecret&&config.operatorSecret){const treasury=keypair(config.treasurySecret).publicKey.toBase58();const {rows:available}=await db.query("SELECT l.id,l.zec_address,COALESCE(s.total,0)::text AS swept,COALESCE(p.total,0)::text AS reserved FROM launches l LEFT JOIN (SELECT launch_id,sum(amount_raw) AS total FROM fee_sweeps WHERE status='confirmed' GROUP BY launch_id) s ON s.launch_id=l.id LEFT JOIN (SELECT launch_id,sum(amount_raw) AS total FROM native_payouts WHERE status NOT IN ('refunded','failed') GROUP BY launch_id) p ON p.launch_id=l.id WHERE l.status='confirmed' AND l.reward_mode='creator' ORDER BY l.confirmed_at LIMIT 25");for(const row of available){try{let amount=BigInt(row.swept)-BigInt(row.reserved);if(amount<config.minPayout)continue;amount=amount>config.maxPayout?config.maxPayout:amount;requireThat(await chain.tokenBalance(treasury)>=amount,503,'Treasury ZEC is below recorded liabilities');await db.query("INSERT INTO native_payouts(id,launch_id,amount_raw,destination) VALUES($1,$2,$3,$4)",[randomUUID(),row.id,String(amount),row.zec_address])}catch(error){console.error(JSON.stringify({event:'payout_reserve_retry',launchId:row.id,code:error.code||error.name}))}}}
 const {rows:payouts}=await db.query("SELECT * FROM native_payouts WHERE status IN ('reserved','quoted','submitted','processing') ORDER BY created_at LIMIT 15");
 for(const item of payouts){try{if(!config.nativePayoutsEnabled||!config.oneClickApiKey||!config.treasurySecret||!config.operatorSecret)continue;const treasury=keypair(config.treasurySecret);let current=item;if(item.status==='reserved'){const quote=await bridge.quote(item.amount_raw,item.destination);current=(await db.query("UPDATE native_payouts SET status='quoted',deposit_address=$2,quote_json=$3,updated_at=now() WHERE id=$1 RETURNING *",[item.id,quote.depositAddress,JSON.stringify(quote)])).rows[0]}
  if(current.status==='quoted'){const q=current.quote_json;if(Date.parse(q.result.quote.deadline)<Date.now()+25000){await db.query("UPDATE native_payouts SET status='needs_review',error='Quote expired before deposit; no transfer was submitted' WHERE id=$1",[item.id]);continue}requireThat(q.payload.amount===String(current.amount_raw)&&q.payload.recipient===current.destination&&q.payload.refundTo===treasury.publicKey.toBase58()&&q.depositAddress===current.deposit_address,500,'Bridge quote has changed');requireThat(await chain.tokenBalance(treasury.publicKey.toBase58())>=BigInt(current.amount_raw),503,'Insufficient treasury balance for reserved payout');const signed=await chain.move({source:config.treasurySecret,destination:current.deposit_address,amount:BigInt(current.amount_raw)});current=(await db.query("UPDATE native_payouts SET status='submitted',solana_signature=$2,solana_wire=$3,solana_last_valid_height=$4,updated_at=now() WHERE id=$1 RETURNING *",[item.id,signed.signature,signed.wire,signed.lastValidHeight])).rows[0]}
  if(current.status==='submitted'){const result=await chain.state(current.solana_signature,current.solana_last_valid_height);if(result==='failed'||result==='expired'){await db.query("UPDATE native_payouts SET status='needs_review',error='Solana transfer failed; reconcile treasury before releasing reserve' WHERE id=$1",[item.id]);continue}if(result==='pending'){await chain.send(current.solana_wire).catch(()=>{});continue}await db.query("UPDATE native_payouts SET status='processing',updated_at=now() WHERE id=$1",[item.id])}
  const result=await bridge.status(current.deposit_address,current.quote_json?.result?.quote?.depositMemo);if(result.status==='SUCCESS'){const hash=result.swapDetails?.destinationChainTxHashes?.find(x=>x.hash)?.hash,amount=result.swapDetails?.amountOut;requireThat(hash&&/^\d+$/.test(String(amount))&&BigInt(amount)>0n,503,'Bridge success lacks native ZEC receipt');await db.query("UPDATE native_payouts SET status='confirmed',zec_txid=$2,native_amount_raw=$3,updated_at=now() WHERE id=$1",[item.id,hash,amount])}else if(result.status==='REFUNDED'||result.status==='FAILED'||result.status==='INCOMPLETE_DEPOSIT')await db.query("UPDATE native_payouts SET status='needs_review',error=$2,updated_at=now() WHERE id=$1",[item.id,`Bridge reported ${result.status}; verify refund before another payout`]);else if(!['PENDING_DEPOSIT','KNOWN_DEPOSIT_TX','PROCESSING'].includes(result.status))throw Error('Unknown bridge status')
 }catch(error){console.error(JSON.stringify({event:'payout_retry',id:item.id,code:error.code||error.name}))}}
}

if(import.meta.url===`file://${process.argv[1]}`){const config=configuration(),db=database(config),chain=createChain(config),bridge=oneClick(config);await db.migrate();let stopped=false;for(const signal of ['SIGINT','SIGTERM'])process.on(signal,()=>{stopped=true});while(!stopped){try{await db.locked(()=>tick({db,config,chain,bridge}))}catch(error){console.error(JSON.stringify({event:'worker_error',code:error.code||error.name}))}if(!stopped)await new Promise(resolve=>setTimeout(resolve,10000))}await db.close()}
